modLoader="javafml"

loaderVersion="[34,)"

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="cutandcolored"

version="4.0"

displayName="Cut And Colored"

updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/cut-and-colored"

logoFile="pack.png"

credits="Me the mod author (Programer), SpiderKolo (Artist)"

authors="MincraftEinstein, SpiderKolo"

description='''
Adds a bunch of stairs, slabs and color variation to blocks in default Minecraft
'''

[[dependencies.cutandcolored]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.cutandcolored]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.cutandcolored]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[1.4,)"
    ordering="AFTER"
    side="BOTH"
