modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="cutandcolored"
	version="8.1"
	displayName="Cut And Colored"
	#updateJSONURL="http://myurl.me/"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cut-and-colored"
	logoFile="pack.png"
	credits="Me the mod author (Programer), SpiderKolo (Artist)"
	authors="MincraftEinstein, SpiderKolo"
	description='''
Adds a bunch of stairs, slabs and color variation to blocks in default Minecraft
'''

[modproperties.cutandcolored]
	catalogueImageIcon="pack.png"
	configuredBackground="cutandcolored:textures/block/light_blue_stained_planks.png"

[[dependencies.cutandcolored]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cutandcolored]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cutandcolored]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"
