modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="cutandcolored"
	version="4.0"
	displayName="Cut And Colored"
	updateJSONURL="http://myurl.me/"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cut-and-colored"
	logoFile="pack.png"
	credits="Me the mod author (Programer), SpiderKolo (Artist)"
	authors="MincraftEinstein, SpiderKolo"
	description='''
Adds a bunch of stairs, slabs and color variation to blocks in default Minecraft
'''

[[dependencies.cutandcolored]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cutandcolored]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.cutandcolored]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[1.4,)"
    ordering="AFTER"
    side="BOTH"
