package einstein.cutandcolored.init;

import einstein.cutandcolored.CutAndColored;
import einstein.cutandcolored.block.ColoredRedstoneLamp;
import einstein.cutandcolored.block.GlassSlabBlock;
import einstein.cutandcolored.block.GlassStairsBlock;
import einstein.einsteins_library.util.RegistryHandler;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.StairsBlock;
import net.minecraft.block.WallBlock;
import net.minecraft.block.material.Material;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = CutAndColored.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class FlamboyantBlocks
{	
	/************************GLASS***************************/
    // STAIRS
	public static final Block AMBER_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block BEIGE_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block CREAM_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block DARK_GREEN_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block FOREST_GREEN_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block HOT_PINK_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block INDIGO_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block MAROON_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block NAVY_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block OLIVE_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_GREEN_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_PINK_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_YELLOW_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block SKY_BLUE_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block SLATE_GRAY_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block VIOLET_STAINED_GLASS_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_glass_stairs", new GlassStairsBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);

    // SLAB
	public static final Block AMBER_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block BEIGE_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block CREAM_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block DARK_GREEN_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block FOREST_GREEN_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block HOT_PINK_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block INDIGO_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block MAROON_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block NAVY_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block OLIVE_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_GREEN_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_PINK_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block PALE_YELLOW_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block SKY_BLUE_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block SLATE_GRAY_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	public static final Block VIOLET_STAINED_GLASS_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_glass_slab", new GlassSlabBlock(Blocks.GLASS::getDefaultState, Block.Properties.from(Blocks.GLASS)), CutAndColored.MOD_TAB);
	
    /*************************WOOL**************************/
    // STAIRS
    public static final Block AMBER_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block CREAM_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block MAROON_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block NAVY_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_WOOL_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL::getDefaultState, Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    
    // SLABS
    public static final Block AMBER_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block CREAM_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block MAROON_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block NAVY_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_WOOL_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_wool_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_WOOL)), CutAndColored.MOD_TAB);

    /*******************STAINED_PLANKS**********************/
    // FULL BLOCKS
	public static final Block AMBER_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block BEIGE_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block CREAM_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block DARK_GREEN_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block FOREST_GREEN_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block HOT_PINK_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block INDIGO_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block MAROON_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block NAVY_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block OLIVE_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block PALE_GREEN_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block PALE_PINK_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block PALE_YELLOW_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block SKY_BLUE_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block SLATE_GRAY_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	public static final Block VIOLET_STAINED_PLANKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_planks", new Block(Block.Properties.create(Material.WOOD).hardnessAndResistance(2.0f, 3.0f).sound(SoundType.WOOD)), CutAndColored.MOD_TAB);
	
    // STAIRS
    public static final Block AMBER_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.AMBER_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.AMBER_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.BEIGE_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.BEIGE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block CREAM_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.CREAM_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.CREAM_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.DARK_GREEN_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.DARK_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.FOREST_GREEN_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.FOREST_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.HOT_PINK_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.HOT_PINK_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.INDIGO_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.INDIGO_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block MAROON_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.MAROON_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.MAROON_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block NAVY_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.NAVY_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.NAVY_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.OLIVE_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.OLIVE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.PALE_GREEN_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.PALE_PINK_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_PINK_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.PALE_YELLOW_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_YELLOW_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.SKY_BLUE_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.SKY_BLUE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.SLATE_GRAY_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.SLATE_GRAY_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_STAINED_PLANK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_plank_stairs", new StairsBlock(FlamboyantBlocks.VIOLET_STAINED_PLANKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.VIOLET_STAINED_PLANKS)), CutAndColored.MOD_TAB);
	
	// SLABS
    public static final Block AMBER_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.AMBER_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.BEIGE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block CREAM_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.CREAM_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.DARK_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.FOREST_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.HOT_PINK_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.INDIGO_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block MAROON_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.MAROON_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block NAVY_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.NAVY_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.OLIVE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_GREEN_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_PINK_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_YELLOW_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.SKY_BLUE_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.SLATE_GRAY_STAINED_PLANKS)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_STAINED_PLANK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_plank_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.VIOLET_STAINED_PLANKS)), CutAndColored.MOD_TAB);
	
    /*********************TERRACOTTA************************/
    // STAIRS
    public static final Block AMBER_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block CREAM_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block MAROON_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block NAVY_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_TERRACOTTA_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA::getDefaultState, Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    
    // SLABS
    public static final Block AMBER_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block CREAM_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block MAROON_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block NAVY_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_TERRACOTTA_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_terracotta_slab", new SlabBlock(Block.Properties.from(Blocks.TERRACOTTA)), CutAndColored.MOD_TAB);
    
    /**********************CONCRETE*************************/
    // STAIRS
    public static final Block AMBER_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block CREAM_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block MAROON_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block NAVY_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_CONCRETE_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE::getDefaultState, Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    
    // SLABS
    public static final Block AMBER_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block CREAM_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block MAROON_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block NAVY_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_CONCRETE_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_concrete_slab", new SlabBlock(Block.Properties.from(Blocks.WHITE_CONCRETE)), CutAndColored.MOD_TAB);
    
    /*******************STAINED_BRICKS**********************/
    // FULL BLOCKS
	public static final Block AMBER_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block BEIGE_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block CREAM_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block DARK_GREEN_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block FOREST_GREEN_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block HOT_PINK_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block INDIGO_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block MAROON_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block NAVY_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block OLIVE_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block PALE_GREEN_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block PALE_PINK_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block PALE_YELLOW_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block SKY_BLUE_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block SLATE_GRAY_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	public static final Block VIOLET_STAINED_BRICKS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_bricks", new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), CutAndColored.MOD_TAB);
	
    // STAIRS
    public static final Block AMBER_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.AMBER_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.AMBER_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.BEIGE_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.BEIGE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block CREAM_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.CREAM_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.CREAM_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.DARK_GREEN_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.DARK_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.FOREST_GREEN_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.FOREST_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.HOT_PINK_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.HOT_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.INDIGO_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.INDIGO_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block MAROON_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.MAROON_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.MAROON_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block NAVY_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.NAVY_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.NAVY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.OLIVE_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.OLIVE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.PALE_GREEN_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.PALE_PINK_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.PALE_YELLOW_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.PALE_YELLOW_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.SKY_BLUE_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.SKY_BLUE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.SLATE_GRAY_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.SLATE_GRAY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_STAINED_BRICK_STAIRS = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_brick_stairs", new StairsBlock(FlamboyantBlocks.VIOLET_STAINED_BRICKS::getDefaultState, Block.Properties.from(FlamboyantBlocks.VIOLET_STAINED_BRICKS)), CutAndColored.MOD_TAB);
	
    // SLABS
    public static final Block AMBER_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.AMBER_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.BEIGE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block CREAM_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.CREAM_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.DARK_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.FOREST_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.HOT_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.INDIGO_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block MAROON_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.MAROON_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block NAVY_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.NAVY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.OLIVE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.PALE_YELLOW_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.SKY_BLUE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.SLATE_GRAY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_STAINED_BRICK_SLAB = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_brick_slab", new SlabBlock(Block.Properties.from(FlamboyantBlocks.VIOLET_STAINED_BRICKS)), CutAndColored.MOD_TAB);
	
	// WALLS
    public static final Block AMBER_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.AMBER_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.BEIGE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block CREAM_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.CREAM_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.DARK_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.FOREST_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.HOT_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.INDIGO_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block MAROON_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.MAROON_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block NAVY_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.NAVY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.OLIVE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.PALE_GREEN_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.PALE_PINK_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.PALE_YELLOW_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.SKY_BLUE_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.SLATE_GRAY_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_STAINED_BRICK_WALL = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_stained_brick_wall", new WallBlock(Block.Properties.from(FlamboyantBlocks.VIOLET_STAINED_BRICKS)), CutAndColored.MOD_TAB);
    
	/************************LAMPS**************************/
    public static final Block AMBER_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "amber_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block BEIGE_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "beige_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block CREAM_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "cream_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block DARK_GREEN_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "dark_green_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block FOREST_GREEN_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "forest_green_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block HOT_PINK_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "hot_pink_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block INDIGO_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "indigo_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block MAROON_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "maroon_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block NAVY_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "navy_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block OLIVE_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "olive_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block PALE_GREEN_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_green_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block PALE_PINK_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_pink_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block PALE_YELLOW_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "pale_yellow_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block SKY_BLUE_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "sky_blue_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block SLATE_GRAY_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "slate_gray_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
    public static final Block VIOLET_REDSTONE_LAMP = RegistryHandler.registerModCompatBlock(CutAndColored.MODID, CutAndColored.FMODID, "violet_redstone_lamp", new ColoredRedstoneLamp(Blocks.REDSTONE_LAMP::getDefaultState, Block.Properties.from(Blocks.REDSTONE_LAMP)), CutAndColored.MOD_TAB);
}
